name: Build and deploy Typst PDFs to GitHub pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Typst setup
        uses: typst-community/setup-typst@v4
      
      - name: Compile Typst files
        run: |
          mkdir -p output
          for file in $(find . -type f -name "*.typ"); do
            typst compile "$file" "output/$(basename "$file" .typ).pdf" --root .
          done


      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: output/*.pdf

  deploy:

    needs: build
  
    permissions:
      pages: write
      id-token: write
        
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'compiled-pdfs'

